services:
  - type: web
    name: felt-and-friends-poker
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
